apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-echo
  labels:
    app: {{ template "fullname" . }}
    component: echo
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: echo
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "fullname" . }}
          component: igor
    ports:
    - port: 8089
