apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-front50
  labels:
    app: {{ template "fullname" . }}
    component: front50
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: front50
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "fullname" . }}
          component: orca
    - podSelector:
        matchLabels:
          app: {{ template "fullname" . }}
          component: echo
    - podSelector:
        matchLabels:
          app: {{ template "fullname" . }}
          component: gate
    ports:
    - port: 8080
