apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-igor
  labels:
    app: {{ template "fullname" . }}
    component: igor
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: igor
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "fullname" . }}
          component: jenkins
    ports:
    - port: 8080
  - ports:
    # Allow access to jenkins UI
    - port: 8088
    # Allow build image to hit it I guess
    #- port: 5000
