apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-rosco
  labels:
    app: {{ template "fullname" . }}
    component: rosco
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
      component: rosco
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ template "fullname" . }}
          component: gate
    ports:
    - port: 8087
