{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ .Values.networkPolicy.apiVersion }}
metadata:
  name: "{{ template "fullname" . }}"
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: 6379
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "fullname" . }}-client: "true"
      {{- end }}
    {{- if .Values.metrics.enabled }}
    # Allow prometheus scrapes for metrics
    - ports:
      - port: 9121
    {{- end }}
{{- end }}
