{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ .Values.networkPolicy.apiVersion }}
metadata:
  name: "{{ template "fullname" . }}"
spec:
  podSelector:
    matchLabels:
      app: "{{ template "fullname" . }}"
  ingress:
    # Allow inbound connections
    - ports:
      - port: 5432
    {{- if not .Values.networkPolicy.allowExternal }}
      from:
      - podSelector:
          matchLabels:
            {{ template "fullname" . }}-client: "true"
    {{- end }}
    # Allow prometheus scrapes
    - ports:
      - port: 9187
{{- end }}
